### ISSUE TITLE
Changing tagVersionStrategy may wipe away existing version data

### ISSUE THREAD

**Issue by erikmunson** [spinnaker/keel#1099]
Last week I had someone change their `tagVersionStrategy` from the default  to `semver-job-commit-by-semver`. What I _believe_ I saw happen was that after the change to the manifest was upserted, we lost all the previously stored version data. For example, versions that I thought  previously had `replacedAt`/`replacedBy`, `deployedAt` etc. all switched to having a `skipped` state with no metdata.

I say I _think_ that's what I saw because it was someone else's app so I hadn't really seen it before and didn't expect anything bad was going to happen so wasn't paying close attention to the UI/API beforehand.

If I saw what I thought I saw, it seems likely that something about the new tag strategy led to us seeing things as new/different versions. I think it should be pretty simple to attempt to reproduce, since there's only one step (change the version strategy).

**Comment by luispollo** [comment]
I'm pretty confident this was fixed by #1105. Please reopen if you disagree.

**Comment by erikmunson** [comment]
yeah i actually just caught a tagVersionStrategy change in action this morning and can confirm I still see accurate historical data from before the strategy change. thanks!
